---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	question_understanding(question_understanding)
	personalization(personalization)
	router(router)
	clarification(clarification)
	retrieval(retrieval)
	tutor(tutor)
	evaluation(evaluation)
	__end__([<p>__end__</p>]):::last
	__start__ --> question_understanding;
	clarification --> evaluation;
	personalization --> retrieval;
	question_understanding --> router;
	retrieval --> tutor;
	router -. &nbsp;clarify&nbsp; .-> clarification;
	router -. &nbsp;tutor&nbsp; .-> personalization;
	tutor --> evaluation;
	evaluation --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
